#pragma once
#include <windows.h>
#include<iostream>
#include<time.h>
#include<vector>
#include<list>
//#include"resource.h"
using namespace std;

enum
{
	ID_R1 = 101,
	ID_R2,
	ID_R3,
};

enum BLOCK_FILENUM
{
	BLOCK_FILENUM_N = 0,
	BLOCK_FILENUM_N_UP,
	BLOCK_FILENUM_N_LEFT,
	BLOCK_FILENUM_N_DOWN,
	BLOCK_FILENUM_N_RIGHT,
	BLOCK_FILENUM_GRASS,
	BLOCK_FILENUM_ICE,
	BLOCK_FILENUM_WATER,
	BLOCK_FILENUM_METAL,
	BLOCK_FILENUM_METAL_UP,
	BLOCK_FILENUM_METAL_LEFT,
	BLOCK_FILENUM_METAL_DOWN,
	BLOCK_FILENUM_METAL_RIGHT,
	BLOCK_FILENUM_CMD,
	BLOCK_FILENUM_CMD_DIE,
};

enum EXPLOSION_FILENUM
{
	EXPLOSION_FILENUM_0 = 0,
	EXPLOSION_FILENUM_1,
	EXPLOSION_FILENUM_2,
	EXPLOSION_FILENUM_3,
	EXPLOSION_FILENUM_4
};

enum SHILED_FILENUM
{
	SHILED_FILENUM_0 = 0,
	SHILED_FILENUM_1
};